### ISSUE TITLE
objects are hidden when zooming to the highest level

### ISSUE THREAD

**Issue by m0yellow** [plepe/OpenStreetBrowser-basemap#5]
When zooming from 17 to 18, objects disappear. In this case nearly half a city block seems to be empty. Zooming back out, and the building and pathway are back.
Browser (not the latest) Safari on (not the latest) OS X.

here are screenshots and links to the first place I noticed it. But it seems to happen somewhere else as well.
![screen shot 2015-03-06 at 21 27 16](https://cloud.githubusercontent.com/assets/2116846/6535740/9e1330c2-c447-11e4-8e55-a1d7d496227c.png)
![screen shot 2015-03-06 at 21 27 08](https://cloud.githubusercontent.com/assets/2116846/6535741/9e22b362-c447-11e4-8421-189cd2205b3b.png)

http://openstreetbrowser.org/?zoom=17&lat=48.15229&lon=16.28853&basemap=osb&categories=&layers=&overlays=

http://openstreetbrowser.org/?zoom=18&lat=48.15229&lon=16.28853&basemap=osb&categories=&layers=&overlays=

**Comment by plepe** [comment]
Check again, now the buildings are there. You just happened to find some outdated tiles, which needed re-rendering. They are not regularly re-rendered, but after they are accessed.

**Comment by m0yellow** [comment]
hey cool, could this happen again? or does it need an indicator for not available tiles?

**Comment by plepe** [comment]
Oh, didn't notice who you are, only from Github mail notification ;)

Yes, it happens all the time. The problem is, that the world is huge and it's not possible to keep all tiles up-to-date. There are also large parts of the world which are not rendered, and maybe will never be. Additionally, my rendering queue is not fast enough to render on-the-fly.

Currently, tiles will be rerendered when they are more than three months old (if I have load on the server, e.g. because of a new database import I increase this timestamp to four months). I'd like to have a zoom level dependant tile limit (as changes are more visible on higher zoom levels), but somehow the configuration does not work. I'll look into it again when I have more time.

At least, now I have a platform which is pretty easy to maintain (pgmapcss / OpenStreetBrowser-basemap) and to clone.

About tiles:
* http://wiki.openstreetmap.org/wiki/Tile_Disk_Usage
